<?php
use Application\Controller\CoreController;
?>
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-10">
                <?php
                $sIcon = (array_key_exists('task-icon',CoreController::$aGlobalSettings))
                    ?  CoreController::$aGlobalSettings['task-icon'] : '';
                ?>
                <?= $this->partial('partial/indexheader',['sTitle'=>'Task','sIcon' => $sIcon]) ?>
            </div>
            <div class="col-md-2 text-right">
                <select class="form-control plc-index-load-saved-search">
                    <option>-- <?=$this->translate('All')?> --</option>
                    <?php
                    if (count($aSavedSearches) > 0) {
                        foreach($aSavedSearches as $oSearch) { ?>
                            <option value="<?=$oSearch->Search_ID?>">
                                <?=$oSearch->label?>
                            </option>
                            <?php
                        }
                    }
                    ?>
                </select>
            </div>
        </div>
    </div>
    <div class="card-body py-0">
        <?= $this->partial('partial/indextable', [
            'sTableName' => $sTableName,
            'aItems' => $aItems,
            'aFilters' => $aFilters,
            'sRoute' => $sRoute
        ]); ?>
    </div>
    <div class="card-footer">
        <?= $this->partial('partial/indexpager', ['aItems'=>$aItems,'sRoute'=>$sRoute]); ?>
    </div>
</div>